In [2]:
import numpy as np

In [3]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [4]:
l1 = [2,4,6,8]
np_arr = np.array(l1)
print(type(np_arr))
print(np_arr/2)

<class 'numpy.ndarray'>
[1. 2. 3. 4.]


In [5]:
l1 = [1,2]
l2 = [3,4]
np_arr1 = np.array(l1)
np_arr2 = np.array(l2)
print(np_arr1*np_arr2)

[3 8]


In [6]:
arr = np.array([[1,2,3], [4,5,6]]) #2D array / matrix
print(arr)

[[1 2 3]
 [4 5 6]]


In [25]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]]) # 3D array
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
l1 = np.array([2,4,6,8])
print(len(l1))
print(l1.size)
print(l1.shape)


4
4
(4,)


In [23]:
arr = np.array([[1,2,3], [4,5,6]])
print(len(arr))
print(arr.size)
print(arr.shape)

2
6
(2, 3)


In [24]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(len(arr))
print(arr.size)
print(arr.shape)

3
9
(3, 3)


In [27]:
arr = np.array([1,2,3,4,5,6,7])
print(np.sort(arr)[::-1])

[7 6 5 4 3 2 1]


In [28]:
arr = np.array([[3,2,4], [5,0,1]])
print(np.sort(arr)) # sort row wise

[[2 3 4]
 [0 1 5]]


In [29]:
arr = np.array([[3,2,4], [6,0,1]])
print(arr.max()) # max val of all elements
print(arr.max(axis=0)) # max val in each col
print(arr.max(axis=1)) # max val in each row
print(arr.min()) # min val of all elements
print(arr.min(axis=0)) # min val in each col
print(arr.min(axis=1)) # min val in each row

6
[6 2 4]
[4 6]
0
[3 0 1]
[2 0]


In [31]:
arr = np.array([5,2,3,4,7,6,1])
print(np.argmax(arr))

4


In [32]:
arr = np.array([5,2,3,4,7,6,1])
print(np.argmin(arr))

6


In [33]:
arr = np.array([[3,2,4], [1,0,9]])
print(np.argmax(arr))
                

5


In [34]:
arr = np.array([[3,2,4], [1,0,9]])
print(np.argmax(arr, axis=1)) # row wise

[2 2]


In [35]:
arr = np.array([5,2,3,4,7,6,1])
print(np.argsort(arr)) # indices sorted

[6 1 2 3 0 5 4]


In [36]:
arr = np.array([5,2,3,4,7,6,1])
print(np.argsort(arr)[::-1]) # indices sorted in reverse

[4 5 0 3 2 1 6]


In [37]:
r = np.array([5,2,3,4,7,6,1])
print(np.argsort(arr)[::-1][:3]) # indices of 3 max val

[4 5 0]


In [39]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(3,4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [41]:
nd1 = np.array([[1,2,3], [4,5,6]])
print(np.reshape(nd1,(1,-1))) # reshape to 1 row, multiple col

[[1 2 3 4 5 6]]


In [42]:
nd1 = np.array([[1,2,3], [4,5,6]])
print(np.reshape(nd1,(-1,1))) # reshape to 1 col, multiple row

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [45]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr[arr % 2 == 1])

[1 3 5 7 9]


In [49]:
arr = np.arange(10)
out = np.where(arr % 2 == 1 ,-1, arr)
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [51]:
arr = np.arange(10)
print(arr)
print(arr.reshape(2,-1))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
