In [2]:
num = int(input("Enter a number:"))
if num % 2 == 1:
    print("The number", num, "is odd")
else:
    print("The number", num, "is even")

Enter a number:8
The number 8 is even


In [27]:
num = int(input("Enter a number:"))
if num == 0 or num == 1:
    print(num,"is not a prime number")
elif num > 1:
    for i in range(2,num):
        if(num % i) == 0:
            print(num, "is not a prime number")
            break
    else:
        print(num, "is a prime number")

Enter a number:8
8 is not a prime number


In [29]:
n = int(input("Enter a number:"))
def getsum(n):
    sum = 0
    for digit in str(n):
        sum += int(digit)
    return sum
print(getsum(n))

Enter a number:111
3


In [34]:
s = input("Enter a word:")
def isPalindrome(s):
    return s == s[::-1]

ans = isPalindrome(s)
if ans:
    print("yes")
else:
    print("no")

Enter a word:Mom
no


In [55]:
import numpy as np
arr = np.array([[], [],[]])
app1 = (np.append(1,2))
app2 = (np.append(3,4))
app3 = (np.append(5,6))
arr = np.array([[app1], [app2],[app3]])
print(arr)

[[[1 2]]

 [[3 4]]

 [[5 6]]]


In [89]:
l2=[[]]
for i in range(0,3):
     
    l1=[]
    for j in range(0,2):
        x = int(input("Enter a number:"))
        l1.append(x)
    l2.append(l1)
print(l2)

Enter a number:67
Enter a number:98
Enter a number:96
Enter a number:23
Enter a number:54
Enter a number:76
[[], [67, 98], [96, 23], [54, 76]]
